//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacSyKSK
    {
        public int MaBacSyKSK { get; set; }
        public string TenBacSyKSK { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<bool> Xoa { get; set; }
    }
}
