//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoSungPhamViHDCM
    {
        public int MaBoSungPhamViHDCM { get; set; }
        public int MaLyLichVienChuc { get; set; }
        public string SoQuyetDinh { get; set; }
        public System.DateTime NgayCap { get; set; }
        public string NoiDungBoSung { get; set; }
    
        public virtual LyLichVienChuc LyLichVienChuc { get; set; }
    }
}
