//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeTaiSangKien
    {
        public int MaDeTaiSangKien { get; set; }
        public string TenDeTaiSangKien { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> MaNhanVien1 { get; set; }
        public Nullable<int> MaNhanVien2 { get; set; }
        public Nullable<int> MaNhanVien3 { get; set; }
        public Nullable<int> MaNhanVien4 { get; set; }
        public string KinhPhi { get; set; }
        public Nullable<System.DateTime> TuThang { get; set; }
        public Nullable<System.DateTime> DenThang { get; set; }
        public string CapDeTai { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<bool> NgayXoa { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual NhanVien NhanVien2 { get; set; }
        public virtual NhanVien NhanVien3 { get; set; }
        public virtual NhanVien NhanVien4 { get; set; }
    }
}
