//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDinhKemWeb
    {
        public int MaFile { get; set; }
        public int MaBaiViet { get; set; }
        public string TenFile { get; set; }
        public string TenFileFull { get; set; }
        public string PhanMoRong { get; set; }
        public System.DateTime NgayTaiLen { get; set; }
        public bool Xoa { get; set; }
    }
}
