//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiNhan
    {
        public int ID { get; set; }
        public int MaBaiViet { get; set; }
        public int NguoiGui { get; set; }
        public int NguoiNhan { get; set; }
        public Nullable<bool> DaNhan { get; set; }
        public Nullable<bool> DaXem { get; set; }
        public Nullable<bool> QuanTrong { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
