//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HinhAnh()
        {
            this.BaiVietWeb = new HashSet<BaiVietWeb>();
        }
    
        public int MaHinhAnh { get; set; }
        public Nullable<int> MaLyLichVienChuc { get; set; }
        public string LoaiHinhAnh { get; set; }
        public string TenFile { get; set; }
        public string TenFileDayDu { get; set; }
        public string DuongDan { get; set; }
        public string PhanMoRong { get; set; }
        public Nullable<System.DateTime> NgayTaiLen { get; set; }
        public Nullable<int> MaBaiViet { get; set; }
        public Nullable<bool> Xoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiVietWeb> BaiVietWeb { get; set; }
    }
}
