//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        public int MaHinhAnh { get; set; }
        public string LoaiHinhAnh { get; set; }
        public string TenFile { get; set; }
        public string TenFileDayDu { get; set; }
        public string DuongDan { get; set; }
        public string PhanMoRong { get; set; }
        public int ChieuRong { get; set; }
        public int ChieuCao { get; set; }
        public bool Xoa { get; set; }
    }
}
