
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PHCN.NhanVien.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LoaiBaiViet
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LoaiBaiViet()
    {

        this.BaiViet = new HashSet<BaiViet>();

    }


    public int MaLoai { get; set; }

    public string TenLoai { get; set; }

    public int STT { get; set; }

    public string MauSac { get; set; }

    public bool Xoa { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BaiViet> BaiViet { get; set; }

}

}
