//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuotKSK
    {
        public int MaLuotKSK { get; set; }
        public int MaSoKSK { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string TienSuBenhTat { get; set; }
        public Nullable<int> TL_ChieuCao { get; set; }
        public Nullable<int> TL_CanNang { get; set; }
        public Nullable<decimal> TL_ChiSoBMI { get; set; }
        public Nullable<int> TL_Mach { get; set; }
        public string TL_HuyetAp { get; set; }
        public string TL_PhanLoaiTheLuc { get; set; }
        public string LS_NoiKhoa_TuanHoan { get; set; }
        public string LS_NoiKhoa_TuanHoan_PhanLoai { get; set; }
        public string LS_NoiKhoa_HoHap { get; set; }
        public string LS_NoiKhoa_HoHap_PhanLoai { get; set; }
        public string LS_NoiKhoa_TieuHoa { get; set; }
        public string LS_NoiKhoa_TieuHoa_PhanLoai { get; set; }
        public string LS_NoiKhoa_ThanTietNieu { get; set; }
        public string LS_NoiKhoa_ThanTietNieu_PhanLoai { get; set; }
        public string LS_NoiKhoa_NoiTiet { get; set; }
        public string LS_NoiKhoa_NoiTiet_PhanLoai { get; set; }
        public string LS_NoiKhoa_CoXuongKhop { get; set; }
        public string LS_NoiKhoa_CoXuongKhop_PhanLoai { get; set; }
        public string LS_NoiKhoa_ThanKinh { get; set; }
        public string LS_NoiKhoa_ThanKinh_PhanLoai { get; set; }
        public string LS_NoiKhoa_TamThan { get; set; }
        public string LS_NoiKhoa_ThamThan_PhanLoai { get; set; }
        public string LS_NoiKhoa_BacSiKy { get; set; }
        public string LS_NgoaiKhoa { get; set; }
        public string LS_NgoaiKhoa_PhanLoai { get; set; }
        public string LS_NgoaiKhoa_BacSiKy { get; set; }
        public string LS_SanPhuKhoa { get; set; }
        public string LS_SanPhuKhoa_PhanLoai { get; set; }
        public string LS_SanPhuKhoa_BacSiKy { get; set; }
        public string LS_Mat_KhongKinhMatPhai { get; set; }
        public string LS_Mat_KhongKinhMatTrai { get; set; }
        public string LS_Mat_CoKinhMatPhai { get; set; }
        public string LS_Mat_CoKinhMatTrai { get; set; }
        public string LS_Mat_CacBenhVeMat { get; set; }
        public string LS_Mat_PhanLoai { get; set; }
        public string LS_Mat_BacSiKy { get; set; }
        public string LS_TaiMuiHong_TaiTraiNoiThuong { get; set; }
        public string LS_TaiMuiHong_TaiTraiNoiTham { get; set; }
        public string LS_TaiMuiHong_TaiPhaiNoiThuong { get; set; }
        public string LS_TaiMuiHong_TaiPhaiNoiTham { get; set; }
        public string LS_TaiMuiHong_CacBenhVeTaiMuiHong { get; set; }
        public string LS_TaiMuiHong_PhanLoai { get; set; }
        public string LS_TaiMuiHong_BacSiKy { get; set; }
        public string LS_RangHamMat_HamTren { get; set; }
        public string LS_RangHamMat_HamDuoi { get; set; }
        public string LS_RangHamMat_CacBenhVeRangHamMat { get; set; }
        public string LS_RangHamMat_PhanLoai { get; set; }
        public string LS_RangHamMat_BacSiKy { get; set; }
        public string LS_DaLieu { get; set; }
        public string LS_DaLieu_PhanLoai { get; set; }
        public string LS_DaLieu_BacSiKy { get; set; }
        public string CLS_XetNghiemMau_HongCau { get; set; }
        public string CLS_XetNghiemMau_BachCau { get; set; }
        public string CLS_XetNghiemMau_TieuCau { get; set; }
        public string CLS_XetNghiemMau_HCT { get; set; }
        public string CLS_XetNghiemMau_Glucose { get; set; }
        public string CLS_XetNghiemMau { get; set; }
        public string CLS_XetNghiemNuocTieu_Glucose { get; set; }
        public string CLS_XetNghiemNuocTieu_Protein { get; set; }
        public string CLS_XetNghiemNuocTieu_pH { get; set; }
        public string CLS_XetNghiemNuocTieu { get; set; }
        public string CLS_XetNghiemPhan { get; set; }
        public string CLS_CacXetNghiemKhac { get; set; }
        public string CLS_DanhGia { get; set; }
        public string CLS_BacSiKy { get; set; }
        public string KL_PhanLoaiSucKhoe { get; set; }
        public string KL_PhanLoaiSucKhoe_GhiChu { get; set; }
        public string KL_CacBenhTatNeuCo { get; set; }
        public string KL_NoiKy { get; set; }
        public Nullable<System.DateTime> KL_NgayKy { get; set; }
        public string KL_NguoiKetLuan { get; set; }
        public Nullable<int> MaNhanVienNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
    
        public virtual SoKSK SoKSK { get; set; }
    }
}
