//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.BaiViet = new HashSet<BaiViet>();
            this.BaiViet1 = new HashSet<BaiViet>();
            this.BaiVietWeb = new HashSet<BaiVietWeb>();
            this.DeTaiSangKien = new HashSet<DeTaiSangKien>();
            this.DeTaiSangKien1 = new HashSet<DeTaiSangKien>();
            this.DeTaiSangKien2 = new HashSet<DeTaiSangKien>();
            this.DeTaiSangKien3 = new HashSet<DeTaiSangKien>();
            this.DeTaiSangKien4 = new HashSet<DeTaiSangKien>();
            this.GuiNhan = new HashSet<GuiNhan>();
            this.GuiNhan1 = new HashSet<GuiNhan>();
            this.LyLichVienChuc = new HashSet<LyLichVienChuc>();
            this.PhanQuyen = new HashSet<PhanQuyen>();
            this.SoKSK = new HashSet<SoKSK>();
        }
    
        public int MaNhanVien { get; set; }
        public string MaKhoa { get; set; }
        public string ChucVu { get; set; }
        public string HoTen { get; set; }
        public string TenDangNhap { get; set; }
        public int STT { get; set; }
        public bool Xoa { get; set; }
        public bool NhanThu { get; set; }
        public string MatKhauMD5 { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string SoDienThoaiNoiBo { get; set; }
        public Nullable<bool> CoCauNhanSu { get; set; }
        public string MatKhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiViet> BaiViet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiViet> BaiViet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiVietWeb> BaiVietWeb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeTaiSangKien> DeTaiSangKien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeTaiSangKien> DeTaiSangKien1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeTaiSangKien> DeTaiSangKien2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeTaiSangKien> DeTaiSangKien3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeTaiSangKien> DeTaiSangKien4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuiNhan> GuiNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuiNhan> GuiNhan1 { get; set; }
        public virtual KhoaPhong KhoaPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LyLichVienChuc> LyLichVienChuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanQuyen> PhanQuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoKSK> SoKSK { get; set; }
    }
}
