//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoKSK_Benh
    {
        public int MaBenh { get; set; }
        public int MaSoKSK { get; set; }
        public string TenBenh { get; set; }
        public bool BenhNgheNghiep { get; set; }
        public int PhatHienNam { get; set; }
    }
}
