//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHCN.NhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TomTatQuaTrinhCongTac
    {
        public int MaTomTatQuaTrinhCongTac { get; set; }
        public int MaLyLichVienChuc { get; set; }
        public Nullable<int> Tu_Thang { get; set; }
        public Nullable<int> Tu_Nam { get; set; }
        public Nullable<int> Den_Thang { get; set; }
        public byte[] Den_Nam { get; set; }
        public string NoiDungCongTac { get; set; }
    
        public virtual LyLichVienChuc LyLichVienChuc { get; set; }
    }
}
